-- AlterTable
ALTER TABLE "Employe" ADD COLUMN     "heuresSupp" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "heuresTravail" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "soldeConges" INTEGER NOT NULL DEFAULT 0;
